# Generated by Django 4.0.5 on 2022-07-23 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import users.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('full_name', models.CharField(max_length=150, validators=[users.utils._full_name_validator], verbose_name="повне ім'я")),
                ('email', models.EmailField(error_messages={'unique': 'Користувач із такою поштою вже існує'}, max_length=254, unique=True, verbose_name='електронна пошта')),
                ('is_admin', models.BooleanField(default=False, verbose_name='чи є адміністратором')),
                ('is_active', models.BooleanField(default=False, verbose_name='чи підтвердив користувач пошту')),
            ],
            options={
                'verbose_name': 'Користувач',
                'verbose_name_plural': 'Користувачі',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserRoleApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True, verbose_name='повідомлення від користувача')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='institutions.object')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запит на отримання ролі користувачем',
                'verbose_name_plural': 'Запити на отримання ролі користувачів',
                'db_table': 'users_roles_applications',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255, verbose_name='посада')),
                ('object_has_access_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_roles', to='institutions.object')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Роль користувача',
                'verbose_name_plural': 'Ролі користувача',
                'db_table': 'users_roles',
            },
        ),
    ]
