# Generated by Django 4.1.1 on 2022-10-02 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrole',
            old_name='object_has_access_to',
            new_name='facility_has_access_to',
        ),
    ]
