# Generated by Django 4.0.5 on 2022-06-28 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userregistrationdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistrationrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_requests', to='users.userregistrationdata'),
        ),
    ]
