# Generated by Django 4.1.1 on 2022-10-03 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_rename_facilities_facility'),
        ('users', '0003_alter_userrole_facility_has_access_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrole',
            old_name='position',
            new_name='position_name',
        ),
        migrations.AlterField(
            model_name='userrole',
            name='facility_has_access_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_roles', to='institutions.facility'),
        ),
    ]
