# Generated by Django 4.0.5 on 2022-06-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userregistrationrequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Користувач із такою поштою вже існує'}, max_length=254, unique=True, verbose_name='електронна пошта'),
        ),
        migrations.AlterModelTable(
            name='userregistrationdata',
            table='users_registration_data',
        ),
    ]
