# Generated by Django 4.1.3 on 2022-12-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0004_rename_position_userrole_position_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='position_name',
            field=models.CharField(max_length=255, verbose_name='Назва посади'),
        ),
    ]
