# Generated by Django 4.0.5 on 2022-06-29 08:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_alter_accesslevel_options_alter_institution_options_and_more'),
        ('users', '0004_alter_user_email_alter_userregistrationdata_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRegistrationRequest',
            new_name='UserRoleApplication',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Користувач', 'verbose_name_plural': 'Користувачі'},
        ),
        migrations.AlterModelOptions(
            name='userregistrationdata',
            options={'verbose_name': 'Дані реєстрації користувача', 'verbose_name_plural': 'Дані реєстрації користувача'},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'verbose_name': 'Роль користувача', 'verbose_name_plural': 'Ролі користувача'},
        ),
        migrations.AlterModelOptions(
            name='userroleapplication',
            options={'verbose_name': 'Запит на отримання ролі користувачем', 'verbose_name_plural': 'Запити на отримання ролі користувачів'},
        ),
        migrations.AddField(
            model_name='userregistrationdata',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='дата подання заяви'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='userroleapplication',
            table='users_role_applications',
        ),
    ]
