# Generated by Django 4.0.5 on 2022-06-29 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_userregistrationrequest_userroleapplication_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregistrationdata',
            old_name='registration_date',
            new_name='applied_at',
        ),
    ]
