# Generated by Django 4.0.5 on 2022-06-29 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userroleapplication_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userregistrationdata',
            options={'verbose_name': 'Дані реєстрації користувача', 'verbose_name_plural': 'Дані реєстрації користувачів'},
        ),
        migrations.RemoveField(
            model_name='userregistrationdata',
            name='email_confirmed',
        ),
    ]
