# Generated by Django 4.0.5 on 2022-07-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_userregistrationdata_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='чи підтвердив користувач пошту'),
        ),
        migrations.DeleteModel(
            name='UserRegistrationData',
        ),
    ]
