# Generated by Django 4.1.1 on 2022-10-02 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_rename_facilities_facility'),
        ('energy', '0003_alter_boxsensorsset_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxsensorsset',
            name='date_set_in',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='boxsensorsset',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box_sensors_set', to='institutions.facility'),
        ),
        migrations.AlterField(
            model_name='boxsensorsset',
            name='sensor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='energy.sensor'),
        ),
    ]
