# Generated by Django 4.1.3 on 2022-12-19 11:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('energy', '0004_alter_boxsensorsset_date_set_in_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='box',
            old_name='box_number',
            new_name='box_identifier',
        ),
        migrations.AlterField(
            model_name='boxsensorsset',
            name='sensor',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name='+', to='energy.sensor'
                ),
        ),
        migrations.AlterField(
            model_name='boxsensorsset',
            name='sensor_number',
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(16)]
                ),
        ),
    ]
