# Generated by Django 4.1.3 on 2023-01-16 12:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('energy', '0006_alter_boxsensorsset_sensor_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxsensorsset',
            name='box',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='box_sensor_sets',
                to='energy.box'
                ),
        ),
        migrations.AlterField(
            model_name='boxsensorsset',
            name='sensor_number_in_set',
            field=models.IntegerField(
                db_column='sensor_number', validators=[django.core.validators.MinValueValidator(0),
                                                       django.core.validators.MaxValueValidator(0)]
                ),
        ),
    ]
