# Generated by Django 4.1.3 on 2023-01-16 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('energy', '0007_alter_boxsensorsset_box_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxsensorsset',
            name='sensor_number_in_set',
            field=models.IntegerField(db_column='sensor_number',
                                      validators=[django.core.validators.MinValueValidator(1),
                                                  django.core.validators.MaxValueValidator(16)]
                                      ),
        ),
    ]
