# Generated by Django 4.1.5 on 2023-01-23 10:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('institutions', '0003_rename_facilities_facility'),
        ('energy', '0008_alter_boxsensorsset_sensor_number_in_set'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BoxSensorsSet',
            new_name='BoxSensorSet',
        ),
    ]
