# Generated by Django 4.1.5 on 2023-01-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('energy', '0009_rename_boxsensorsset_boxsensorset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='box_description',
            field=models.TextField(db_column='box_description'),
        ),
        migrations.RenameField(
            model_name='box',
            old_name='box_description',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='box',
            name='box_identifier',
            field=models.CharField(db_column='box_identifier', max_length=256),
        ),
        migrations.RenameField(
            model_name='box',
            old_name='box_identifier',
            new_name='identifier',
        ),
    ]
