# Generated by Django 4.1 on 2023-10-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('energy', '0012_alter_boxsensorset_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='identifier',
            field=models.CharField(db_column='box_identifier', max_length=256, unique=True),
        ),
    ]
