# Generated by Django 4.2 on 2025-02-04 13:13

import django.core.validators
from django.db import migrations, models
import energy.logic.box_identifier_validation


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0013_alter_box_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='identifier',
            field=models.CharField(db_column='box_identifier', max_length=256, unique=True, validators=[energy.logic.box_identifier_validation.validate_box_identifier]),
        ),
        migrations.AlterField(
            model_name='boxsensorset',
            name='sensor_number_in_set',
            field=models.IntegerField(db_column='sensor_number', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
