# Generated by Django 4.0.4 on 2022-06-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('institution_id', models.AutoField(db_column='institution_id', primary_key=True, serialize=False)),
                ('institution_name', models.CharField(max_length=1000)),
                ('institution_description', models.TextField()),
            ],
            options={
                'db_table': 'institutions',
            },
        ),
    ]
