# Generated by Django 4.0.5 on 2022-06-29 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesslevel',
            options={'verbose_name': 'Рівень доступу', 'verbose_name_plural': 'Рівні доступу'},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'verbose_name': 'Заклад', 'verbose_name_plural': 'Заклади'},
        ),
        migrations.AlterModelOptions(
            name='object',
            options={'verbose_name': "Об'єкт", 'verbose_name_plural': "Об'єкти"},
        ),
    ]
