# Generated by Django 4.0.5 on 2022-07-25 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Object',
            new_name='Facilities',
        ),
        migrations.AlterModelTable(
            name='facilities',
            table='facilities',
        ),
    ]
