# Generated by Django 4.0.4 on 2022-06-20 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_accesslevel_objects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Objects',
            new_name='Object',
        ),
    ]
