# Generated by Django 4.0.4 on 2022-06-20 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_rename_objects_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='institutions.object'),
        ),
    ]
