# Generated by Django 4.0.4 on 2022-06-20 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0005_alter_object_access_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_objects', to='institutions.institution'),
        ),
    ]
